### PR TITLE
Batch address geocoder job provides only country name, not country_id

### PR DESCRIPTION
**Pull request by mfb**
I found that the batch address geocoder job only provides `country` name parameter, not `country_id`

Perhaps this should be fixed upstream in Civi core.. but I made a somewhat hacky workaround.

### CODE REVIEW

**Comment by mfb** [comment]
@eileenmcnaughton think I should also patch this upstream in civi core? The geocode job could/should provide country_id to geocoders.

**Comment by eileenmcnaughton** [comment]
@mfb that seems reasonable - would it still be needed here if we do that?

**Comment by mfb** [comment]
I added https://github.com/civicrm/civicrm-core/pull/13456 - if/when that goes in, this PR won't be needed.

**Comment by eileenmcnaughton** [comment]
Note this was fixed via a core PR

**Pull request closed without merging**
