### PR TITLE
Fix Spelling of OpenStreetMap

### PR DESCRIPTION
**Pull request by datendelphin**
Hi

Thank you for this nice CiviCRM extension. We will use it for the OpenStreetMap foundation membership register. That is the reason why I stumbled over the spelling in the readme. I suggest these fixes to correct the spelling of OpenStreetMap (no spaces, no s at the end)

Thanks

### CODE REVIEW

**Comment by datendelphin** [comment]
Would it be possible to also fix the spelling on https://civicrm.org/extensions/geocoder?

**Comment by eileenmcnaughton** [comment]
I did the page update too

**Comment by datendelphin** [comment]
Awesome, thanks! There is still on instance of "Open street maps" on the extensions page under Default Configuration, 2)

**Comment by eileenmcnaughton** [comment]
thanks @datendelphin  - fixed

**Pull request merged**
